name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [ 16, 18, 20 ]

    steps:
    - uses: actions/checkout@v4

    # - name: Setup node | ${{ matrix.node }}
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        # node-version: ${{ matrix.node }}
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run test

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Container Registry login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # - name: Build docker image
    #   run: docker build -t ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:${{ steps.generate_tag.outputs.sha }} .

    # - name: Push image to Container Registry
    #   run: docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:${{ steps.generate_tag.outputs.sha }}

    - name: Build docker image and push image to Container Registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:${{ steps.generate_tag.outputs.sha }}, ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:latest