name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci
    - run: npm run test

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Configure AWS Credentials
      uses: ws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
    
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build
      env: 
        CONTAINER_REGISTRY_URL: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      run: |
        docker build -t $CONTAINER_REGISTRY_URL/rocket-ci:$TAG .
        docker push $CONTAINER_REGISTRY_URL/rocket-ci:$TAG

    # - name: Build docker image and push image to Container Registry
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:${{ steps.generate_tag.outputs.sha }}, ${{ secrets.CONTAINER_REGISTRY_URL }}/rocketdevops-ci-api:latest